# Generated by Django 4.1.4 on 2023-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_host",
            field=models.BooleanField(default=False),
        ),
    ]
